# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.10
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 3 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      # 3. <Linux, Release, latest Clang compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [clang-22]
        include:
          - os: ubuntu-latest
            c_compiler: clang-22
            cpp_compiler: clang++-22
            cpp_flags: "-stdlib=libc++ -static"
            cmake_flags: -DCMAKE_CXX_STDLIB_MODULES_JSON=/usr/lib/llvm-22/lib/libc++.modules.json
        exclude: []

    steps:
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y cmake ninja-build python-is-python3 python3-venv libboost-system-dev libboost-dev wget lsb-release software-properties-common gnupg git 
    - name: Install CMake
      uses: ssrobins/install-cmake@v1
      with:
        version: 4.1.1
    - name: Install Clang 22
      if: matrix.c_compiler == 'clang-22'
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        ./llvm.sh 22
        apt install -y libc++-22-dev
        mkdir -p /lib/share/libc++/
        ln -s /usr/lib/llvm-22/share/libc++/v1 /lib/share/libc++/v1
    - name: Install GCC
      if: matrix.c_compiler == 'gcc'
      run: |
        wget --quiet https://kayari.org/gcc-latest/gcc-latest.deb \
        && dpkg -i gcc-latest.deb
        echo "/opt/gcc-latest/bin" >> $GITHUB_PATH
        echo "LD_RUN_PATH=/opt/gcc-latest/lib64" >> $GITHUB_ENV


    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B build
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_CXX_FLAGS="${{ matrix.cpp_flags }}"
        ${{ matrix.cmake_flags }}
        -GNinja
        -S .

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      # Execute tests defined by the CMake configuration. Note that --build-config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest --build-config ${{ matrix.build_type }}
    - uses: actions/upload-artifact@v4
      with:
        name: build
        path: build/web_irc
